# Generated by Django 4.2.7 on 2025-05-17 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='Número de caso al que pertenece la evidencia', max_length=50, verbose_name='número de caso')),
                ('code', models.CharField(help_text='Código único de la evidencia', max_length=50, unique=True, verbose_name='código de evidencia')),
                ('description', models.TextField(help_text='Descripción detallada de la evidencia', verbose_name='descripción')),
                ('type', models.CharField(choices=[('DOCUMENT', 'Documento'), ('PHOTO', 'Fotografía'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('OBJECT', 'Objeto físico'), ('DIGITAL', 'Evidencia digital'), ('SAMPLE', 'Muestra biológica'), ('OTHER', 'Otro')], default='OBJECT', help_text='Tipo de evidencia', max_length=20, verbose_name='tipo')),
                ('location_found', models.CharField(help_text='Lugar donde se encontró la evidencia', max_length=255, verbose_name='lugar encontrado')),
                ('date_found', models.DateTimeField(help_text='Fecha y hora en que se encontró la evidencia', verbose_name='fecha y hora encontrada')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Buena'), ('FAIR', 'Regular'), ('POOR', 'Mala'), ('DAMAGED', 'Dañada')], default='GOOD', help_text='Estado de la evidencia', max_length=20, verbose_name='condición')),
                ('packaging', models.CharField(help_text='Tipo de embalaje utilizado', max_length=255, verbose_name='embalaje')),
                ('storage_location', models.CharField(help_text='Ubicación actual de almacenamiento', max_length=255, verbose_name='ubicación de almacenamiento')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre la evidencia', verbose_name='notas')),
                ('photo', models.ImageField(blank=True, help_text='Fotografía de la evidencia', null=True, upload_to='evidences/%Y/%m/', verbose_name='fotografía')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Indicar si la evidencia es de naturaleza sensible', verbose_name='es sensible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('collector', models.ForeignKey(help_text='Persona que recolectó la evidencia', on_delete=django.db.models.deletion.PROTECT, related_name='collected_evidences', to=settings.AUTH_USER_MODEL, verbose_name='recolector')),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('reason', models.CharField(help_text='Motivo del cambio de custodia', max_length=255, verbose_name='motivo')),
                ('destination', models.CharField(help_text='Destino o ubicación después del traspaso', max_length=255, verbose_name='destino')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el traspaso', verbose_name='notas')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_chain', to='evidence.evidence', verbose_name='evidencia')),
                ('handed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handed_evidences', to=settings.AUTH_USER_MODEL, verbose_name='entregado por')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_evidences', to=settings.AUTH_USER_MODEL, verbose_name='recibido por')),
            ],
            options={
                'verbose_name': 'cadena de custodia',
                'verbose_name_plural': 'cadenas de custodia',
                'ordering': ['-date'],
            },
        ),
    ]
