# Generated by Django 4.2.7 on 2025-06-19 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('view', 'Visualización'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportación')], max_length=20, verbose_name='acción')),
                ('content_type', models.CharField(help_text='Tipo de objeto afectado (ej: Evidencia, Usuario, etc.)', max_length=50, verbose_name='tipo de contenido')),
                ('object_id', models.CharField(blank=True, help_text='Identificador del objeto afectado', max_length=50, null=True, verbose_name='id de objeto')),
                ('details', models.TextField(blank=True, help_text='Detalles adicionales de la acción', verbose_name='detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registros de actividad',
                'ordering': ['-timestamp'],
            },
        ),
    ]
