# Generated by Django 4.2.7 on 2025-06-20

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='backups/%Y/%m/%d/', verbose_name='Archivo de backup')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de backup')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], default='manual', max_length=20, verbose_name='Tipo de backup')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
                'ordering': ['-fecha'],
            },
        ),
    ] 