# Generated by Django 4.2.7 on 2025-06-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operative', 'Operativo'), ('administrative', 'Administrativo')], default='operative', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='rol'),
        ),
    ]
